// Questions AOUV (Action ou Vérité) - PLUS DE 200 QUESTIONS
const aouvQuestions = {
    action: [
        "Imite un animal de ton choix pendant 30 secondes",
        "Chante une chanson populaire en faisant des gestes",
        "Fais 10 pompes (ou 5 si tu ne peux pas)",
        "Danse comme si personne ne te regardait",
        "Raconte une blague très drôle",
        "Fais le plus beau sourire possible",
        "Imite une célébrité que tout le monde connaît",
        "Fais une déclaration d'amour à un objet dans la pièce",
        "Parle avec un accent étranger pendant 1 minute",
        "Fais une poignée de main invisible",
        "Fais une tour avec 3 objets autour de toi",
        "Mange quelque chose de bizarre (si disponible)",
        "Fais une battle de rap improvisé",
        "Fais une annonce publicitaire pour un produit imaginaire",
        "Fais le bruit d'un animal pendant 20 secondes",
        "Fais une statue vivante pendant 30 secondes",
        "Fais une déclaration poétique à ton voisin",
        "Fais un tour de magie simple",
        "Fais une imitation de ton prof préféré",
        "Fais une danse traditionnelle de ton pays",
        "Fais une présentation de mode avec tes vêtements",
        "Fais une interview imaginaire",
        "Fais une critique de film inventé",
        "Fais une recette de cuisine imaginaire",
        "Fais une forecast météo imaginaire",
        "Fais une publicité pour un produit absurde",
        "Fais une transformation de super-héros",
        "Fais une scène de film romantique",
        "Fais une battle de danse silencieuse",
        "Fais une imitation de robot",
        "Fais une scène de comédie stand-up",
        "Fais une présentation d'invention absurde",
        "Fais une transformation en animal",
        "Fais une scène de film d'action",
        "Fais une imitation de personnage de dessin animé",
        "Fais une battle de chant improvisé",
        "Fais une scène de film d'horreur",
        "Fais une imitation de présentateur TV",
        "Fais une transformation en monstre",
        "Fais une scène de film comique",
        "Fais une imitation de star de la musique",
        "Fais une battle de mime",
        "Fais une scène de film de science-fiction",
        "Fais une imitation de personnage historique",
        "Fais une transformation en super-vilain",
        "Fais une scène de film dramatique",
        "Fais une imitation de sportif célèbre",
        "Fais une battle de poésie",
        "Fais une scène de film d'aventure",
        "Fais une imitation de personnage politique",
        "Fais une transformation en extraterrestre",
        "Fais une scène de film fantastique",
        "Fais une imitation de chef cuisinier",
        "Fais une battle de devinettes",
        "Fais une scène de film policier",
        "Fais une imitation de scientifique",
        "Fais une transformation en pirate",
        "Fais une scène de film de guerre",
        "Fais une imitation de personnage de jeu vidéo",
        "Fais une battle de charades",
        "Fais une scène de film musical",
        "Fais une imitation de magicien",
        "Fais une transformation en ninja",
        "Fais une scène de film western",
        "Fais une imitation de pilote",
        "Fais une battle de blagues",
        "Fais une scène de film d'animation",
        "Fais une imitation de détective privé",
        "Fais une transformation en vampire",
        "Fais une scène de film de romance",
        "Fais une imitation de rock star",
        "Fais une battle de devinettes musicales",
        "Fais une scène de film de comédie musicale",
        "Fais une imitation de présentateur météo",
        "Fais une transformation en fantôme",
        "Fais une scène de film de thriller",
        "Fais une imitation de commentateur sportif",
        "Fais une battle de citations célèbres",
        "Fais une scène de film de famille",
        "Fais une imitation de journaliste",
        "Fais une transformation en sorcier",
        "Fais une scène de film d'amitié",
        "Fais une imitation d'animateur radio",
        "Fais une battle de mots drôles",
        "Fais une scène de film d'école",
        "Fais une imitation de vendeur",
        "Fais une transformation en zombie",
        "Fais une scène de film de vacances",
        "Fais une imitation de guide touristique",
        "Fais une battle d'histoires courtes",
        "Fais une scène de film de fête",
        "Fais une imitation de coach sportif",
        "Fais une transformation en ange",
        "Fais une scène de film de travail",
        "Fais une imitation de professeur",
        "Fais une battle de secrets",
        "Fais une scène de film de voyage",
        "Fais une imitation de médecin",
        "Fais une transformation en dragon",
        "Fais une scène de film de rêve",
        "Fais une imitation d'avocat",
        "Fais une battle de défis",
        "Fais une scène de film de cauchemar",
        "Fais une imitation d'artiste",
        "Fais une transformation en licorne",
        "Fais une scène de film de réalité",
        "Fais une imitation de clown",
        "Fais une transformation en alien",
        "Fais une scène de film de mémoire",
        "Fais une imitation de danseur professionnel",
        "Fais une battle de créativité",
        "Fais une scène de film d'imagination",
        "Fais une imitation de comédien",
        "Fais une transformation en super-héros",
        "Fais une scène de film de courage",
        "Fais une imitation de poète",
        "Fais une battle d'originalité",
        "Fais une scène de film de sagesse",
        "Fais une imitation de philosophe",
        "Fais une transformation en dieu",
        "Fais une scène de film de pouvoir",
        "Fais une imitation de roi",
        "Fais une battle de leadership",
        "Fais une scène de film de gloire",
        "Fais une imitation de reine",
        "Fais une transformation en déesse",
        "Fais une scène de film de beauté",
        "Fais une imitation de prince",
        "Fais une battle de noblesse",
        "Fais une scène de film de royauté",
        "Fais une imitation de princesse",
        "Fais une transformation en monarque",
        "Fais une scène de film de couronne",
        "Fais une imitation de chevalier",
        "Fais une battle d'honneur",
        "Fais une scène de film de bravoure",
        "Fais une imitation de guerrier",
        "Fais une transformation en champion",
        "Fais une scène de film de victoire",
        "Fais une imitation de héros",
        "Fais une battle de légende",
        "Fais une scène de film de destin",
        "Fais une imitation de sauveur",
        "Fais une transformation en protecteur",
        "Fais une scène de film de sécurité",
        "Fais une imitation de gardien",
        "Fais une battle de protection",
        "Fais une scène de film de défense",
        "Fais une imitation de défenseur",
        "Fais une transformation en bouclier",
        "Fais une scène de film de force",
        "Fais une imitation de combattant",
        "Fais une battle de combat",
        "Fais une scène de film de bataille",
        "Fais une imitation de stratège",
        "Fais une transformation en général",
        "Fais une scène de film de stratégie",
        "Fais une imitation de commandant",
        "Fais une battle de commandement",
        "Fais une scène de film de discipline",
        "Fais une imitation de soldat",
        "Fais une transformation en armée",
        "Fais une scène de film de puissance",
        "Fais une imitation de capitaine",
        "Fais une battle de marine",
        "Fais une scène de film de navigation",
        "Fais une imitation de navigateur",
        "Fais une transformation en explorateur",
        "Fais une scène de film d'aventure",
        "Fais une imitation d'aventurier",
        "Fais une battle de découverte",
        "Fais une scène de film d'exploration",
        "Fais une imitation d'explorateur",
        "Fais une transformation en pionnier",
        "Fais une scène de film de frontière",
        "Fais une imitation de pionnier",
        "Fais une battle de frontière",
        "Fais une scène de film de colonisation",
        "Fais une imitation de colon",
        "Fais une transformation en colonisateur",
        "Fais une scène de film de civilisation",
        "Fais une imitation de civilisateur",
        "Fais une battle de civilisation",
        "Fais une scène de film de progrès",
        "Fais une imitation d'inventeur",
        "Fais une transformation en innovateur",
        "Fais une scène de film d'innovation",
        "Fais une imitation d'innovateur",
        "Fais une battle d'innovation",
        "Fais une scène de film de technologie",
        "Fais une imitation de technologue",
        "Fais une transformation en technicien",
        "Fais une scène de film de technique",
        "Fais une imitation de technicien",
        "Fais une battle de technique",
        "Fais une scène de film de compétence",
        "Fais une imitation de compétent",
        "Fais une transformation en expert",
        "Fais une scène de film d'expertise",
        "Fais une imitation d'expert",
        "Fais une battle d'expertise",
        "Fais une scène de film de maîtrise",
        "Fais une imitation de maître",
        "Fais une transformation en maître",
        "Fais une scène de film d'apprentissage",
        "Fais une imitation d'élève",
        "Fais une battle d'éducation",
        "Fais une scène de film d'enseignement",
        "Fais une imitation d'enseignant",
        "Fais une transformation en éducateur",
        "Fais une scène de film de pédagogie",
        "Fais une imitation de pédagogue",
        "Fais une battle de pédagogie",
        "Fais une scène de film de formation",
        "Fais une imitation de formateur",
        "Fais une transformation en formateur",
        "Fais une scène de film de coaching",
        "Fais une imitation de coach",
        "Fais une battle de coaching",
        "Fais une scène de film de mentorat",
        "Fais une imitation de mentor",
        "Fais une transformation en mentor",
        "Fais une scène de film de guidance",
        "Fais une imitation de guide",
        "Fais une battle de guidance",
        "Fais une scène de film de direction",
        "Fais une imitation de directeur",
        "Fais une transformation en leader",
        "Fais une scène de film de leadership",
        "Fais une imitation de leader",
        "Fais une battle de leadership"
    ],
    verite: [
        "Quel est ton plus grand secret ?",
        "De qui es-tu secrètement amoureux(se) ?",
        "Quelle est ta plus grande peur ?",
        "Quel est ton regret le plus profond ?",
        "As-tu déjà triché à un examen ?",
        "Quel est le mensonge le plus gros que tu as dit ?",
        "As-tu déjà fait quelque chose d'illégal ?",
        "Quelle est ta chose la plus embarrassante ?",
        "As-tu déjà volé quelque chose ?",
        "Quel est ton rêve le plus fou ?",
        "As-tu déjà eu un coup de foudre ?",
        "Quelle est ta plus grande honte ?",
        "As-tu déjà pleuré devant un film ?",
        "Quel est ton talent caché ?",
        "As-tu déjà fait quelque chose de stupide ?",
        "Quelle est ta plus grande faiblesse ?",
        "As-tu déjà menti à tes parents ?",
        "Quel est ton souvenir d'enfance préféré ?",
        "As-tu déjà eu peur du noir ?",
        "Quelle est ta plus grande force ?",
        "As-tu déjà eu un ami imaginaire ?",
        "Quel est ton plat préféré ?",
        "As-tu déjà mangé quelque chose d'étrange ?",
        "Quelle est ta couleur préférée ?",
        "As-tu déjà eu un animal de compagnie ?",
        "Quel est ton film préféré ?",
        "As-tu déjà vu un film effrayant ?",
        "Quelle est ta chanson préférée ?",
        "As-tu déjà chanté sous la douche ?",
        "Quel est ton livre préféré ?",
        "As-tu déjà lu un livre entier ?",
        "Quelle est ta série préférée ?",
        "As-tu déjà regardé une série en entier ?",
        "Quel est ton jeu vidéo préféré ?",
        "As-tu déjà joué à un jeu vidéo ?",
        "Quelle est ta saison préférée ?",
        "As-tu déjà eu une saison préférée ?",
        "Quel est ton mois préféré ?",
        "As-tu déjà eu un mois préféré ?",
        "Quel est ton jour préféré ?",
        "As-tu déjà eu un jour préféré ?",
        "Quelle est ton heure préférée ?",
        "As-tu déjà eu une heure préférée ?",
        "Quel est ton endroit préféré ?",
        "As-tu déjà eu un endroit préféré ?",
        "Quelle est ta personne préférée ?",
        "As-tu déjà eu une personne préférée ?",
        "Quel est ton animal préféré ?",
        "As-tu déjà eu un animal préféré ?",
        "Quelle est ta plante préférée ?",
        "As-tu déjà eu une plante préférée ?",
        "Quel est ton fruit préféré ?",
        "As-tu déjà eu un fruit préféré ?",
        "Quel est ton légume préféré ?",
        "As-tu déjà eu un légume préféré ?",
        "Quelle est ta boisson préférée ?",
        "As-tu déjà eu une boisson préférée ?",
        "Quel est ton dessert préféré ?",
        "As-tu déjà eu un dessert préféré ?",
        "Quel est ton snack préféré ?",
        "As-tu déjà eu un snack préféré ?",
        "Quelle est ta friandise préférée ?",
        "As-tu déjà eu une friandise préférée ?",
        "Quel est ton fast-food préféré ?",
        "As-tu déjà eu un fast-food préféré ?",
        "Quel est ton restaurant préféré ?",
        "As-tu déjà eu un restaurant préféré ?",
        "Quelle est ta cuisine préférée ?",
        "As-tu déjà eu une cuisine préférée ?",
        "Quel est ton plat traditionnel préféré ?",
        "As-tu déjà eu un plat traditionnel préféré ?",
        "Quelle est ta spécialité locale préférée ?",
        "As-tu déjà eu une spécialité locale préférée ?",
        "Quel est ton sport préféré ?",
        "As-tu déjà fait du sport ?",
        "Quelle est ton activité physique préférée ?",
        "As-tu déjà eu une activité physique préférée ?",
        "Quel est ton exercice préféré ?",
        "As-tu déjà fait un exercice ?",
        "Quelle est ta position de yoga préférée ?",
        "As-tu déjà fait du yoga ?",
        "Quel est ton art martial préféré ?",
        "As-tu déjà fait un art martial ?",
        "Quelle est ta danse préférée ?",
        "As-tu déjà dansé ?",
        "Quel est ton style de danse préféré ?",
        "As-tu déjà eu un style de danse préféré ?",
        "Quel est ton instrument de musique préféré ?",
        "As-tu déjà joué d'un instrument ?",
        "Quelle est ta note de musique préférée ?",
        "As-tu déjà eu une note de musique préférée ?",
        "Quel est ton genre musical préféré ?",
        "As-tu déjà eu un genre musical préféré ?",
        "Quel est ton artiste préféré ?",
        "As-tu déjà eu un artiste préféré ?",
        "Quelle est ta chanson d'enfance préférée ?",
        "As-tu déjà eu une chanson d'enfance préférée ?",
        "Quel est ton hymne préféré ?",
        "As-tu déjà eu un hymne préféré ?",
        "Quelle est ta mélodie préférée ?",
        "As-tu déjà eu une mélodie préférée ?",
        "Quel est ton rythme préféré ?",
        "As-tu déjà eu un rythme préféré ?",
        "Quelle est ta tempo préféré ?",
        "As-tu déjà eu une tempo préféré ?",
        "Quel est ton style musical préféré ?",
        "As-tu déjà eu un style musical préféré ?",
        "Quelle est ta période musicale préférée ?",
        "As-tu déjà eu une période musicale préférée ?",
        "Quel est ton mouvement artistique préféré ?",
        "As-tu déjà eu un mouvement artistique préféré ?",
        "Quelle est ton époque préférée ?",
        "As-tu déjà eu une époque préférée ?",
        "Quel est ton style architectural préféré ?",
        "As-tu déjà eu un style architectural préféré ?",
        "Quelle est ta forme d'art préférée ?",
        "As-tu déjà eu une forme d'art préférée ?",
        "Quel est ton médium artistique préféré ?",
        "As-tu déjà eu un médium artistique préféré ?",
        "Quelle est ta technique artistique préférée ?",
        "As-tu déjà eu une technique artistique préférée ?",
        "Quel est ton outil artistique préféré ?",
        "As-tu déjà eu un outil artistique préféré ?",
        "Quelle est ta matière artistique préférée ?",
        "As-tu déjà eu une matière artistique préférée ?",
        "Quel est ton sujet artistique préféré ?",
        "As-tu déjà eu un sujet artistique préféré ?",
        "Quelle est ton inspiration artistique préférée ?",
        "As-tu déjà eu une inspiration artistique préférée ?",
        "Quel est ton musée préféré ?",
        "As-tu déjà visité un musée ?",
        "Quelle est ton exposition préférée ?",
        "As-tu déjà vu une exposition ?",
        "Quel est ton artiste contemporain préféré ?",
        "As-tu déjà eu un artiste contemporain préféré ?",
        "Quelle est ton œuvre d'art préférée ?",
        "As-tu déjà eu une œuvre d'art préférée ?",
        "Quel est ton chef-d'œuvre préféré ?",
        "As-tu déjà vu un chef-d'œuvre ?",
        "Quelle est ta sculpture préférée ?",
        "As-tu déjà vu une sculpture ?",
        "Quel est ton tableau préféré ?",
        "As-tu déjà vu un tableau ?",
        "Quelle est ta photographie préférée ?",
        "As-tu déjà pris une photographie ?",
        "Quel est ton film préféré ?",
        "As-tu déjà vu ton film préféré ?",
        "Quelle est ta scène de film préférée ?",
        "As-tu déjà eu une scène de film préférée ?",
        "Quel est ton réalisateur préféré ?",
        "As-tu déjà eu un réalisateur préféré ?",
        "Quelle est ton acteur préféré ?",
        "As-tu déjà eu un acteur préféré ?",
        "Quelle est ton actrice préférée ?",
        "As-tu déjà eu une actrice préférée ?",
        "Quel est ton personnage de film préféré ?",
        "As-tu déjà eu un personnage de film préféré ?",
        "Quelle est ta citation de film préférée ?",
        "As-tu déjà eu une citation de film préférée ?",
        "Quel est ton genre de film préféré ?",
        "As-tu déjà eu un genre de film préféré ?",
        "Quelle est ton époque de film préférée ?",
        "As-tu déjà eu une époque de film préférée ?",
        "Quel est ton pays de film préféré ?",
        "As-tu déjà eu un pays de film préféré ?",
        "Quelle est ta langue de film préférée ?",
        "As-tu déjà vu un film en langue étrangère ?",
        "Quel est ton sous-titre de film préféré ?",
        "As-tu déjà lu des sous-titres ?",
        "Quelle est ta bande-son de film préférée ?",
        "As-tu déjà écouté une bande-son ?",
        "Quel est ton thème musical de film préféré ?",
        "As-tu déjà eu un thème musical de film préféré ?",
        "Quelle est ta partition de film préférée ?",
        "As-tu déjà vu une partition ?",
        "Quel est ton compositeur de film préféré ?",
        "As-tu déjà eu un compositeur de film préféré ?",
        "Quelle est ta chanson de film préférée ?",
        "As-tu déjà eu une chanson de film préférée ?",
        "Quel est ton clip vidéo préféré ?",
        "As-tu déjà vu un clip vidéo ?",
        "Quelle est ta séquence de film préférée ?",
        "As-tu déjà eu une séquence de film préférée ?",
        "Quel est ton plan de film préféré ?",
        "As-tu déjà remarqué un plan de film ?",
        "Quelle est ton angle de caméra préféré ?",
        "As-tu déjà remarqué un angle de caméra ?",
        "Quel est ton effet spécial préféré ?",
        "As-tu déjà vu un effet spécial ?",
        "Quelle est ton animation de film préférée ?",
        "As-tu déjà vu une animation ?",
        "Quel est ton dessin animé préféré ?",
        "As-tu déjà vu un dessin animé ?",
        "Quelle est ta série d'animation préférée ?",
        "As-tu déjà vu une série d'animation ?",
        "Quel est ton personnage d'animation préféré ?",
        "As-tu déjà eu un personnage d'animation préféré ?",
        "Quelle est ta voix d'animation préférée ?",
        "As-tu déjà remarqué une voix d'animation ?",
        "Quel est ton studio d'animation préféré ?",
        "As-tu déjà entendu parler d'un studio d'animation ?",
        "Quelle est ta technique d'animation préférée ?",
        "As-tu déjà vu différentes techniques d'animation ?",
        "Quel est ton style d'animation préféré ?",
        "As-tu déjà eu un style d'animation préféré ?",
        "Quelle est ton époque d'animation préférée ?",
        "As-tu déjà vu des animations de différentes époques ?",
        "Quel est ton pays d'animation préféré ?",
        "As-tu déjà vu des animations de différents pays ?",
        "Quelle est ta langue d'animation préférée ?",
        "As-tu déjà vu des animations en différentes langues ?",
        "Quel est ton doublage d'animation préféré ?",
        "As-tu déjà remarqué un doublage d'animation ?",
        "Quelle est ta bande-son d'animation préférée ?",
        "As-tu déjà écouté une bande-son d'animation ?",
        "Quel est ton thème musical d'animation préféré ?",
        "As-tu déjà eu un thème musical d'animation préféré ?",
        "Quelle est ta chanson d'animation préférée ?",
        "As-tu déjà eu une chanson d'animation préférée ?",
        "Quel est ton clip d'animation préféré ?",
        "As-tu déjà vu un clip d'animation ?",
        "Quelle est ta séquence d'animation préférée ?",
        "As-tu déjà eu une séquence d'animation préférée ?",
        "Quel est ton personnage de série préféré ?",
        "As-tu déjà eu un personnage de série préféré ?",
        "Quelle est ta saison de série préférée ?",
        "As-tu déjà eu une saison de série préférée ?",
        "Quel est ton épisode de série préféré ?",
        "As-tu déjà eu un épisode de série préféré ?",
        "Quelle est ta scène de série préférée ?",
        "As-tu déjà eu une scène de série préférée ?",
        "Quel est ta citation de série préférée ?",
        "As-tu déjà eu une citation de série préférée ?",
        "Quel est ton genre de série préféré ?",
        "As-tu déjà eu un genre de série préféré ?",
        "Quelle est ton époque de série préférée ?",
        "As-tu déjà eu une époque de série préférée ?",
        "Quel est ton pays de série préféré ?",
        "As-tu déjà vu des séries de différents pays ?",
        "Quelle est ta langue de série préférée ?",
        "As-tu déjà vu des séries en différentes langues ?",
        "Quel est ton créateur de série préféré ?",
        "As-tu déjà eu un créateur de série préféré ?",
        "Quelle est ta production de série préférée ?",
        "As-tu déjà entendu parler d'une production ?",
        "Quel est ton réseau de diffusion préféré ?",
        "As-tu déjà regardé différents réseaux ?",
        "Quelle est ta plateforme de streaming préférée ?",
        "As-tu déjà utilisé différentes plateformes ?",
        "Quel est ton abonnement préféré ?",
        "As-tu déjà eu un abonnement ?",
        "Quelle est ta recommandation de série préférée ?",
        "As-tu déjà reçu une recommandation ?",
        "Quel est ton avis de série préféré ?",
        "As-tu déjà donné un avis ?",
        "Quelle est ta critique de série préférée ?",
        "As-tu déjà lu une critique ?",
        "Quel est ton forum de série préféré ?",
        "As-tu déjà participé à un forum ?",
        "Quelle est ta communauté de série préférée ?",
        "As-tu déjà rejoint une communauté ?",
        "Quel est ton fan club de série préféré ?",
        "As-tu déjà rejoint un fan club ?",
        "Quelle est ta convention de série préférée ?",
        "As-tu déjà assisté à une convention ?",
        "Quel est ton merchandise de série préféré ?",
        "As-tu déjà acheté du merchandise ?",
        "Quelle est ta collection de série préférée ?",
        "As-tu déjà eu une collection ?",
        "Quel est ton poster de série préféré ?",
        "As-tu déjà eu un poster ?",
        "Quelle est ta figurine de série préférée ?",
        "As-tu déjà eu une figurine ?",
        "Quel est ton t-shirt de série préféré ?",
        "As-tu déjà eu un t-shirt ?",
        "Quelle est ta tasse de série préférée ?",
        "As-tu déjà eu une tasse ?",
        "Quel est ton stylo de série préféré ?",
        "As-tu déjà eu un stylo ?",
        "Quelle est ta clé USB de série préférée ?",
        "As-tu déjà eu une clé USB ?",
        "Quel est ton coque de téléphone de série préférée ?",
        "As-tu déjà eu une coque ?",
        "Quelle est ta peau de téléphone de série préférée ?",
        "As-tu déjà eu une peau ?",
        "Quel est ton fond d'écran de série préféré ?",
        "As-tu déjà eu un fond d'écran ?",
        "Quelle est ta sonnerie de série préférée ?",
        "As-tu déjà eu une sonnerie ?",
        "Quelle est ta notification de série préférée ?",
        "As-tu déjà eu une notification ?",
        "Quel est ton emoji de série préféré ?",
        "As-tu déjà utilisé un emoji ?",
        "Quelle est ta GIF de série préférée ?",
        "As-tu déjà utilisé une GIF ?",
        "Quel est ton mème de série préféré ?",
        "As-tu déjà utilisé un mème ?",
        "Quelle est ta citation de série préférée ?",
        "As-tu déjà partagé une citation ?",
        "Quel est ton moment de série préféré ?",
        "As-tu déjà partagé un moment ?",
        "Quelle est ta réaction de série préférée ?",
        "As-tu déjà eu une réaction ?",
        "Quel est ton émotion de série préférée ?",
        "As-tu déjà ressenti une émotion ?",
        "Quel est ton souvenir de série préféré ?",
        "As-tu déjà eu un souvenir ?",
        "Quelle est ton expérience de série préférée ?",
        "As-tu déjà eu une expérience ?",
        "Quel est ton moment de série préféré avec des amis ?",
        "As-tu déjà regardé avec des amis ?",
        "Quelle est ta soirée de série préférée ?",
        "As-tu déjà eu une soirée ?",
        "Quel est ton marathon de série préféré ?",
        "As-tu déjà fait un marathon ?",
        "Quelle est ta discussion de série préférée ?",
        "As-tu déjà eu une discussion ?",
        "Quel est ton débat de série préféré ?",
        "As-tu déjà eu un débat ?",
        "Quelle est ton analyse de série préférée ?",
        "As-tu déjà fait une analyse ?",
        "Quelle est ta théorie de série préférée ?",
        "As-tu déjà eu une théorie ?",
        "Quel est ton spoiler de série préféré ?",
        "As-tu déjà évité les spoilers ?",
        "Quelle est ta révélation de série préférée ?",
        "As-tu déjà eu une révélation ?",
        "Quel est ton twist de série préféré ?",
        "As-tu déjà eu un twist ?",
        "Quelle est ta fin de série préférée ?",
        "As-tu déjà eu une fin préférée ?",
        "Quel est ton cliffhanger de série préféré ?",
        "As-tu déjà eu un cliffhanger ?",
        "Quelle est ta scène post-générique de série préférée ?",
        "As-tu déjà vu une scène post-générique ?",
        "Quel est ton générique de série préféré ?",
        "As-tu déjà regardé un générique ?",
        "Quelle est ta musique de générique de série préférée ?",
        "As-tu déjà écouté une musique de générique ?",
        "Quel est ton visuel de générique de série préféré ?",
        "As-tu déjà remarqué un visuel ?",
        "Quelle est ta police de caractère de série préférée ?",
        "As-tu déjà remarqué une police ?",
        "Quel est ton logo de série préféré ?",
        "As-tu déjà remarqué un logo ?",
        "Quelle est ta branding de série préférée ?",
        "As-tu déjà remarqué un branding ?",
        "Quel est ton marketing de série préféré ?",
        "As-tu déjà vu du marketing ?",
        "Quelle est ta campagne de série préférée ?",
        "As-tu déjà vu une campagne ?",
        "Quelle est ta bande-annonce de série préférée ?",
        "As-tu déjà vu une bande-annonce ?",
        "Quel est ton teaser de série préféré ?",
        "As-tu déjà vu un teaser ?",
        "Quelle est ta promotion de série préférée ?",
        "As-tu déjà vu une promotion ?",
        "Quelle est ton événement de série préféré ?",
        "As-tu déjà assisté à un événement ?",
        "Quelle est ta lancement de série préféré ?",
        "As-tu déjà assisté à un lancement ?",
        "Quelle est ta première de série préférée ?",
        "As-tu déjà assisté à une première ?",
        "Quelle est ton avant-première de série préférée ?",
        "As-tu déjà assisté à une avant-première ?",
        "Quelle est ta projection de série préférée ?",
        "As-tu déjà assisté à une projection ?",
        "Quelle est ta rencontre de série préférée ?",
        "As-tu déjà assisté à une rencontre ?",
        "Quelle est ta signature de série préférée ?",
        "As-tu déjà obtenu une signature ?",
        "Quelle est ta photo de série préférée ?",
        "As-tu déjà pris une photo ?",
        "Quelle est ton autographe de série préféré ?",
        "As-tu déjà obtenu un autographe ?",
        "Quelle est ta vidéo de série préférée ?",
        "As-tu déjà regardé une vidéo ?",
        "Quelle est ton interview de série préférée ?",
        "As-tu déjà regardé une interview ?",
        "Quelle est ton podcast de série préféré ?",
        "As-tu déjà écouté un podcast ?",
        "Quelle est ta radio de série préférée ?",
        "As-tu déjà écouté une radio ?",
        "Quelle est ton article de série préféré ?",
        "As-tu déjà lu un article ?",
        "Quelle est ton blog de série préféré ?",
        "As-tu déjà lu un blog ?",
        "Quelle est ton critique de série préféré ?",
        "As-tu déjà lu une critique ?",
        "Quelle est ton analyse de série préférée ?",
        "As-tu déjà lu une analyse ?",
        "Quelle est ton commentaire de série préféré ?",
        "As-tu déjà lu un commentaire ?",
        "Quelle est ton avis de série préféré ?",
        "As-tu déjà donné un avis ?",
        "Quelle est ta note de série préférée ?",
        "As-tu déjà donné une note ?",
        "Quelle est ton classement de série préféré ?",
        "As-tu déjà fait un classement ?",
        "Quelle est ta liste de série préférée ?",
        "As-tu déjà fait une liste ?",
        "Quelle est ta recommandation de série préférée ?",
        "As-tu déjà fait une recommandation ?",
        "Quelle est ta suggestion de série préférée ?",
        "As-tu déjà fait une suggestion ?",
        "Quelle est ta découverte de série préférée ?",
        "As-tu déjà fait une découverte ?",
        "Quelle est ton exploration de série préférée ?",
        "As-tu déjà fait une exploration ?",
        "Quelle est ton aventure de série préférée ?",
        "As-tu déjà eu une aventure ?",
        "Quelle est ton voyage de série préféré ?",
        "As-tu déjà fait un voyage ?",
        "Quelle est ton escapade de série préférée ?",
        "As-tu déjà eu une escapade ?",
        "Quelle est ton week-end de série préféré ?",
        "As-tu déjà eu un week-end ?",
        "Quelle est ta soirée de série préférée ?",
        "As-tu déjà eu une soirée ?",
        "Quelle est ta nuit de série préférée ?",
        "As-tu déjà eu une nuit ?",
        "Quelle est ton aube de série préférée ?",
        "As-tu déjà eu une aube ?",
        "Quelle est ton crépuscule de série préférée ?",
        "As-tu déjà eu un crépuscule ?",
        "Quelle est ton coucher de soleil de série préférée ?",
        "As-tu déjà vu un coucher de soleil ?",
        "Quelle est ton lever de soleil de série préférée ?",
        "As-tu déjà vu un lever de soleil ?",
        "Quelle est ton étoile de série préférée ?",
        "As-tu déjà vu une étoile ?",
        "Quelle est ta lune de série préférée ?",
        "As-tu déjà vu la lune ?",
        "Quelle est ta constellation de série préférée ?",
        "As-tu déjà vu une constellation ?",
        "Quelle est ta galaxie de série préférée ?",
        "As-tu déjà vu une galaxie ?",
        "Quelle est ton univers de série préférée ?",
        "As-tu déjà exploré un univers ?",
        "Quelle est ta dimension de série préférée ?",
        "As-tu déjà exploré une dimension ?",
        "Quelle est ta réalité de série préférée ?",
        "As-tu déjà exploré une réalité ?",
        "Quelle est ton monde de série préféré ?",
        "As-tu déjà exploré un monde ?",
        "Quelle est ta contrée de série préférée ?",
        "As-tu déjà exploré une contrée ?",
        "Quelle est ta région de série préférée ?",
        "As-tu déjà exploré une région ?",
        "Quelle est ta ville de série préférée ?",
        "As-tu déjà exploré une ville ?",
        "Quelle est ton quartier de série préféré ?",
        "As-tu déjà exploré un quartier ?",
        "Quelle est ta rue de série préférée ?",
        "As-tu déjà exploré une rue ?",
        "Quelle est ta maison de série préférée ?",
        "As-tu déjà exploré une maison ?",
        "Quelle est ta pièce de série préférée ?",
        "As-tu déjà exploré une pièce ?",
        "Quel est ton objet de série préféré ?",
        "As-tu déjà exploré un objet ?",
        "Quelle est ton meuble de série préféré ?",
        "As-tu déjà exploré un meuble ?",
        "Quel est ton outil de série préféré ?",
        "As-tu déjà exploré un outil ?",
        "Quelle est ton arme de série préférée ?",
        "As-tu déjà exploré une arme ?",
        "Quel est ton véhicule de série préféré ?",
        "As-tu déjà exploré un véhicule ?",
        "Quelle est ta technologie de série préférée ?",
        "As-tu déjà exploré une technologie ?",
        "Quel est ton gadget de série préféré ?",
        "As-tu déjà exploré un gadget ?",
        "Quel est ton appareil de série préféré ?",
        "As-tu déjà exploré un appareil ?",
        "Quelle est ta machine de série préférée ?",
        "As-tu déjà exploré une machine ?",
        "Quel est ton robot de série préféré ?",
        "As-tu déjà exploré un robot ?",
        "Quelle est ton IA de série préférée ?",
        "As-tu déjà exploré une IA ?",
        "Quel est ton programme de série préféré ?",
        "As-tu déjà exploré un programme ?",
        "Quelle est ton algorithme de série préféré ?",
        "As-tu déjà exploré un algorithme ?",
        "Quel est ton code de série préféré ?",
        "As-tu déjà exploré un code ?",
        "Quelle est ta clé de série préférée ?",
        "As-tu déjà exploré une clé ?",
        "Quel est ton mot de passe de série préféré ?",
        "As-tu déjà exploré un mot de passe ?",
        "Quelle est ta sécurité de série préférée ?",
        "As-tu déjà exploré une sécurité ?",
        "Quel est ton cryptage de série préféré ?",
        "As-tu déjà exploré un cryptage ?",
        "Quelle est ta protection de série préférée ?",
        "As-tu déjà exploré une protection ?",
        "Quel est ton bouclier de série préféré ?",
        "As-tu déjà exploré un bouclier ?",
        "Quelle est ton armure de série préférée ?",
        "As-tu déjà exploré une armure ?",
        "Quel est ton costume de série préféré ?",
        "As-tu déjà exploré un costume ?",
        "Quelle est ta tenue de série préférée ?",
        "As-tu déjà exploré une tenue ?",
        "Quel est ton vêtement de série préféré ?",
        "As-tu déjà exploré un vêtement ?",
        "Quelle est ta chaussure de série préférée ?",
        "As-tu déjà exploré une chaussure ?",
        "Quel est ton accessoire de série préféré ?",
        "As-tu déjà exploré un accessoire ?",
        "Quel est ton bijou de série préféré ?",
        "As-tu déjà exploré un bijou ?",
        "Quelle est ta montre de série préférée ?",
        "As-tu déjà exploré une montre ?",
        "Quel est ton téléphone de série préféré ?",
        "As-tu déjà exploré un téléphone ?",
        "Quel est ton ordinateur de série préféré ?",
        "As-tu déjà exploré un ordinateur ?",
        "Quelle est ta tablette de série préférée ?",
        "As-tu déjà exploré une tablette ?",
        "Quel est ton écran de série préféré ?",
        "As-tu déjà exploré un écran ?",
        "Quel est ton projecteur de série préféré ?",
        "As-tu déjà exploré un projecteur ?",
        "Quelle est ton caméra de série préférée ?",
        "As-tu déjà exploré une caméra ?",
        "Quel est ton objectif de série préféré ?",
        "As-tu déjà exploré un objectif ?",
        "Quel est ton filtre de série préféré ?",
        "As-tu déjà exploré un filtre ?",
        "Quel est ton effet de série préféré ?",
        "As-tu déjà exploré un effet ?",
        "Quelle est ton animation de série préférée ?",
        "As-tu déjà exploré une animation ?",
        "Quel est ton transition de série préférée ?",
        "As-tu déjà exploré une transition ?",
        "Quelle est ton montage de série préféré ?",
        "As-tu déjà exploré un montage ?",
        "Quel est ton édition de série préférée ?",
        "As-tu déjà exploré une édition ?",
        "Quelle est ton mixage de série préféré ?",
        "As-tu déjà exploré un mixage ?",
        "Quel est ton son de série préféré ?",
        "As-tu déjà exploré un son ?",
        "Quelle est ta musique de série préférée ?",
        "As-tu déjà exploré une musique ?",
        "Quel est ton bruitage de série préféré ?",
        "As-tu déjà exploré un bruitage ?",
        "Quelle est ta voix de série préférée ?",
        "As-tu déjà exploré une voix ?",
        "Quel est ton dialogue de série préféré ?",
        "As-tu déjà exploré un dialogue ?",
        "Quel est ton monologue de série préféré ?",
        "As-tu déjà exploré un monologue ?",
        "Quelle est ta narration de série préférée ?",
        "As-tu déjà exploré une narration ?",
        "Quel est ton histoire de série préférée ?",
        "As-tu déjà exploré une histoire ?",
        "Quel est ton scénario de série préféré ?",
        "As-tu déjà exploré un scénario ?",
        "Quel est ton script de série préféré ?",
        "As-tu déjà exploré un script ?",
        "Quel est ton texte de série préféré ?",
        "As-tu déjà exploré un texte ?",
        "Quelle est ta page de série préférée ?",
        "As-tu déjà exploré une page ?",
        "Quel est ton chapitre de série préféré ?",
        "As-tu déjà exploré un chapitre ?",
        "Quel est ton tome de série préféré ?",
        "As-tu déjà exploré un tome ?",
        "Quel est ton volume de série préféré ?",
        "As-tu déjà exploré un volume ?",
        "Quel est ton livre de série préféré ?",
        "As-tu déjà exploré un livre ?",
        "Quelle est ta bibliothèque de série préférée ?",
        "As-tu déjà exploré une bibliothèque ?",
        "Quel est ton archive de série préférée ?",
        "As-tu déjà exploré une archive ?",
        "Quelle est ta collection de série préférée ?",
        "As-tu déjà exploré une collection ?",
        "Quel est ton musée de série préféré ?",
        "As-tu déjà exploré un musée ?",
        "Quelle est ta galerie de série préférée ?",
        "As-tu déjà exploré une galerie ?",
        "Quel est ton exposition de série préférée ?",
        "As-tu déjà exploré une exposition ?",
        "Quelle est ta vitrine de série préférée ?",
        "As-tu déjà exploré une vitrine ?",
        "Quel est ton affiche de série préférée ?",
        "As-tu déjà exploré une affiche ?",
        "Quelle est ta publicité de série préférée ?",
        "As-tu déjà exploré une publicité ?",
        "Quel est ton annonce de série préférée ?",
        "As-tu déjà exploré une annonce ?",
        "Quelle est ta promotion de série préférée ?",
        "As-tu déjà exploré une promotion ?",
        "Quel est ton événement de série préféré ?",
        "As-tu déjà exploré un événement ?",
        "Quelle est ta célébration de série préférée ?",
        "As-tu déjà exploré une célébration ?",
        "Quel est ton festival de série préféré ?",
        "As-tu déjà exploré un festival ?",
        "Quelle est ta compétition de série préférée ?",
        "As-tu déjà exploré une compétition ?",
        "Quel est ton concours de série préféré ?",
        "As-tu déjà exploré un concours ?",
        "Quel est ton jeu de série préféré ?",
        "As-tu déjà exploré un jeu ?",
        "Quelle est ton activité de série préférée ?",
        "As-tu déjà exploré une activité ?",
        "Quel est ton passe-temps de série préféré ?",
        "As-tu déjà exploré un passe-temps ?",
        "Quel est ton hobby de série préféré ?",
        "As-tu déjà exploré un hobby ?",
        "Quelle est ta passion de série préférée ?",
        "As-tu déjà exploré une passion ?",
        "Quel est ton intérêt de série préféré ?",
        "As-tu déjà exploré un intérêt ?",
        "Quelle est ta curiosité de série préférée ?",
        "As-tu déjà exploré une curiosité ?",
        "Quel est ton désir de série préféré ?",
        "As-tu déjà exploré un désir ?",
        "Quel est ton rêve de série préféré ?",
        "As-tu déjà exploré un rêve ?",
        "Quelle est ton ambition de série préférée ?",
        "As-tu déjà exploré une ambition ?",
        "Quel est ton objectif de série préféré ?",
        "As-tu déjà exploré un objectif ?",
        "Quelle est ton but de série préféré ?",
        "As-tu déjà exploré un but ?",
        "Quel est ton projet de série préféré ?",
        "As-tu déjà exploré un projet ?",
        "Quelle est ton idée de série préférée ?",
        "As-tu déjà exploré une idée ?",
        "Quel est ton concept de série préféré ?",
        "As-tu déjà exploré un concept ?",
        "Quelle est ta théorie de série préférée ?",
        "As-tu déjà exploré une théorie ?",
        "Quel est ton hypothèse de série préférée ?",
        "As-tu déjà exploré une hypothèse ?",
        "Quelle est ta supposition de série préférée ?",
        "As-tu déjà exploré une supposition ?",
        "Quel est ton présupposé de série préféré ?",
        "As-tu déjà exploré un présupposé ?",
        "Quelle est ta prémisse de série préférée ?",
        "As-tu déjà exploré une prémisse ?",
        "Quel est ton postulat de série préféré ?",
        "As-tu déjà exploré un postulat ?",
        "Quel est ton axiome de série préféré ?",
        "As-tu déjà exploré un axiome ?",
        "Quel est ton principe de série préféré ?",
        "As-tu déjà exploré un principe ?",
        "Quel est ton règle de série préféré ?",
        "As-tu déjà exploré une règle ?",
        "Quel est ton loi de série préféré ?",
        "As-tu déjà exploré une loi ?",
        "Quel est ton réglement de série préféré ?",
        "As-tu déjà exploré un réglement ?",
        "Quel est ton directive de série préféré ?",
        "As-tu déjà exploré une directive ?",
        "Quel est ton instruction de série préférée ?",
        "As-tu déjà exploré une instruction ?",
        "Quel est ton ordre de série préféré ?",
        "As-tu déjà exploré un ordre ?",
        "Quel est ton commandement de série préféré ?",
        "As-tu déjà exploré un commandement ?",
        "Quel est ton demande de série préférée ?",
        "As-tu déjà exploré une demande ?",
        "Quel est ton question de série préférée ?",
        "As-tu déjà exploré une question ?",
        "Quel est ton réponse de série préférée ?",
        "As-tu déjà exploré une réponse ?",
        "Quel est ton solution de série préférée ?",
        "As-tu déjà exploré une solution ?",
        "Quel est ton problème de série préféré ?",
        "As-tu déjà exploré un problème ?",
        "Quel est ton défi de série préféré ?",
        "As-tu déjà exploré un défi ?",
        "Quel est ton obstacle de série préféré ?",
        "As-tu déjà exploré un obstacle ?",
        "Quel est ton difficulté de série préférée ?",
        "As-tu déjà exploré une difficulté ?",
        "Quel est ton épreuve de série préférée ?",
        "As-tu déjà exploré une épreuve ?",
        "Quel est ton test de série préféré ?",
        "As-tu déjà exploré un test ?",
        "Quel est ton examen de série préféré ?",
        "As-tu déjà exploré un examen ?",
        "Quel est ton évaluation de série préférée ?",
        "As-tu déjà exploré une évaluation ?",
        "Quel est ton jugement de série préféré ?",
        "As-tu déjà exploré un jugement ?",
        "Quel est ton verdict de série préféré ?",
        "As-tu déjà exploré un verdict ?",
        "Quel est ton sentence de série préférée ?",
        "As-tu déjà exploré une sentence ?",
        "Quel est ton condamnation de série préférée ?",
        "As-tu déjà exploré une condamnation ?",
        "Quel est ton punition de série préférée ?",
        "As-tu déjà exploré une punition ?",
        "Quel est ton sanction de série préférée ?",
        "As-tu déjà exploré une sanction ?",
        "Quel est ton pénalité de série préférée ?",
        "As-tu déjà exploré une pénalité ?",
        "Quel est ton amende de série préférée ?",
        "As-tu déjà exploré une amende ?",
        "Quel est ton dommages de série préférée ?",
        "As-tu déjà exploré des dommages ?",
        "Quel est ton réparation de série préférée ?",
        "As-tu déjà exploré une réparation ?",
        "Quel est ton compensation de série préférée ?",
        "As-tu déjà exploré une compensation ?",
        "Quel est ton indemnisation de série préférée ?",
        "As-tu déjà exploré une indemnisation ?",
        "Quel est ton restitution de série préférée ?",
        "As-tu déjà exploré une restitution ?",
        "Quel est ton remboursement de série préféré ?",
        "As-tu déjà exploré un remboursement ?",
        "Quel est ton remplacement de série préféré ?",
        "As-tu déjà exploré un remplacement ?",
        "Quel est ton substitution de série préférée ?",
        "As-tu déjà exploré une substitution ?",
        "Quel est ton échange de série préféré ?",
        "As-tu déjà exploré un échange ?",
        "Quel est ton troc de série préféré ?",
        "As-tu déjà exploré un troc ?",
        "Quel est ton commerce de série préféré ?",
        "As-tu déjà exploré un commerce ?",
        "Quel est ton marché de série préféré ?",
        "As-tu déjà exploré un marché ?",
        "Quel est ton boutique de série préférée ?",
        "As-tu déjà exploré une boutique ?",
        "Quel est ton magasin de série préféré ?",
        "As-tu déjà exploré un magasin ?",
        "Quel est ton entrepôt de série préféré ?",
        "As-tu déjà exploré un entrepôt ?",
        "Quel est ton dépôt de série préféré ?",
        "As-tu déjà exploré un dépôt ?",
        "Quel est ton stockage de série préféré ?",
        "As-tu déjà exploré un stockage ?",
        "Quel est ton conservation de série préférée ?",
        "As-tu déjà exploré une conservation ?",
        "Quel est ton préservation de série préférée ?",
        "As-tu déjà exploré une préservation ?",
        "Quel est ton protection de série préférée ?",
        "As-tu déjà exploré une protection ?",
        "Quel est ton sécurité de série préférée ?",
        "As-tu déjà exploré une sécurité ?",
        "Quel est ton défense de série préférée ?",
        "As-tu déjà exploré une défense ?",
        "Quel est ton garde de série préféré ?",
        "As-tu déjà exploré un garde ?",
        "Quel est ton surveillance de série préférée ?",
        "As-tu déjà exploré une surveillance ?",
        "Quel est ton contrôle de série préféré ?",
        "As-tu déjà exploré un contrôle ?",
        "Quel est ton inspection de série préférée ?",
        "As-tu déjà exploré une inspection ?",
        "Quel est ton vérification de série préférée ?",
        "As-tu déjà exploré une vérification ?",
        "Quel est ton validation de série préférée ?",
        "As-tu déjà exploré une validation ?",
        "Quel est ton authentification de série préférée ?",
        "As-tu déjà exploré une authentification ?",
        "Quel est ton identification de série préférée ?",
        "As-tu déjà exploré une identification ?",
        "Quel est ton reconnaissance de série préférée ?",
        "As-tu déjà exploré une reconnaissance ?",
        "Quel est ton détection de série préférée ?",
        "As-tu déjà exploré une détection ?",
        "Quel est ton découverte de série préférée ?",
        "As-tu déjà exploré une découverte ?",
        "Quel est ton exploration de série préférée ?",
        "As-tu déjà exploré une exploration ?",
        "Quel est ton investigation de série préférée ?",
        "As-tu déjà exploré une investigation ?",
        "Quel est ton recherche de série préférée ?",
        "As-tu déjà exploré une recherche ?",
        "Quel est ton étude de série préférée ?",
        "As-tu déjà exploré une étude ?",
        "Quel est ton analyse de série préférée ?",
        "As-tu déjà exploré une analyse ?",
        "Quel est ton examen de série préféré ?",
        "As-tu déjà exploré un examen ?",
        "Quel est ton observation de série préférée ?",
        "As-tu déjà exploré une observation ?",
        "Quel est ton surveillance de série préférée ?",
        "As-tu déjà exploré une surveillance ?",
        "Quel est ton monitoring de série préféré ?",
        "As-tu déjà exploré un monitoring ?",
        "Quel est ton suivi de série préféré ?",
        "As-tu déjà exploré un suivi ?",
        "Quel est ton traçabilité de série préférée ?",
        "As-tu déjà exploré une traçabilité ?",
        "Quel est ton historique de série préféré ?",
        "As-tu déjà exploré un historique ?",
        "Quel est ton archive de série préférée ?",
        "As-tu déjà exploré une archive ?",
        "Quel est ton documentation de série préférée ?",
        "As-tu déjà exploré une documentation ?",
        "Quel est ton enregistrement de série préféré ?",
        "As-tu déjà exploré un enregistrement ?",
        "Quel est ton sauvegarde de série préférée ?",
        "As-tu déjà exploré une sauvegarde ?",
        "Quel est ton backup de série préféré ?",
        "As-tu déjà exploré un backup ?",
        "Quel est ton copie de série préférée ?",
        "As-tu déjà exploré une copie ?",
        "Quel est ton duplication de série préférée ?",
        "As-tu déjà exploré une duplication ?",
        "Quel est ton reproduction de série préférée ?",
        "As-tu déjà exploré une reproduction ?",
        "Quel est ton clonage de série préféré ?",
        "As-tu déjà exploré un clonage ?",
        "Quel est ton replication de série préférée ?",
        "As-tu déjà exploré une replication ?",
        "Quel est ton mirroring de série préféré ?",
        "As-tu déjà exploré un mirroring ?",
        "Quel est ton synchronisation de série préférée ?",
        "As-tu déjà exploré une synchronisation ?",
        "Quel est ton mise à jour de série préférée ?",
        "As-tu déjà exploré une mise à jour ?",
        "Quel est ton actualisation de série préférée ?",
        "As-tu déjà exploré une actualisation ?",
        "Quel est ton rafraîchissement de série préférée ?",
        "As-tu déjà exploré un rafraîchissement ?",
        "Quel est ton rechargement de série préféré ?",
        "As-tu déjà exploré un rechargement ?",
        "Quel est ton renouvellement de série préférée ?",
        "As-tu déjà exploré un renouvellement ?",
        "Quel est ton régénération de série préférée ?",
        "As-tu déjà exploré une régénération ?",
        "Quel est ton restauration de série préférée ?",
        "As-tu déjà exploré une restauration ?",
        "Quel est ton réparation de série préférée ?",
        "As-tu déjà exploré une réparation ?",
        "Quel est ton maintenance de série préférée ?",
        "As-tu déjà exploré une maintenance ?",
        "Quel est ton entretien de série préféré ?",
        "As-tu déjà exploré un entretien ?",
        "Quel est ton soin de série préféré ?",
        "As-tu déjà exploré un soin ?",
        "Quel est ton traitement de série préféré ?",
        "As-tu déjà exploré un traitement ?",
        "Quel est ton thérapie de série préférée ?",
        "As-tu déjà exploré une thérapie ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?",
        "Quel est ton guérison de série préférée ?",
        "As-tu déjà exploré une guérison ?"
    ]
}

module.exports = aouvQuestions
